#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=ft_lmhead
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=ft_lmhead_%A.out


module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate iti_gen

# Run your code
srun python -u /home/scur1303/nlp2_sien/results_finetune_kfold_lmhead/finetune.py


